# Generated by Django 2.1 on 2018-08-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=200)),
                ('entry_date', models.DateTimeField(verbose_name='Date Entered')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_name', models.CharField(max_length=200)),
                ('new_name', models.CharField(blank=True, max_length=200)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Case')),
            ],
        ),
    ]
