# Generated by Django 2.1 on 2018-08-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
