# Generated by Django 2.1 on 2018-08-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20180807_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='childs_name',
            field=models.CharField(default='last name', max_length=200, verbose_name='Current last name of adoptive child/Children'),
        ),
        migrations.AddField(
            model_name='case',
            name='your_name',
            field=models.CharField(default='last name', max_length=200, verbose_name="You're last name"),
        ),
    ]
