# Generated by Django 2.1 on 2018-08-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20180807_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kid',
            new_name='Child',
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'children'},
        ),
        migrations.AlterField(
            model_name='case',
            name='childs_name',
            field=models.CharField(max_length=200, verbose_name='Current last name of adoptive child/Children'),
        ),
        migrations.AlterField(
            model_name='case',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Entered'),
        ),
        migrations.AlterField(
            model_name='case',
            name='your_name',
            field=models.CharField(max_length=200, verbose_name="You're last name"),
        ),
    ]
