# Generated by Django 2.1 on 2018-08-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_auto_20180807_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition', models.BooleanField(default=False)),
                ('app_order', models.BooleanField(default=False)),
                ('final_decree', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='childs_name',
            field=models.CharField(max_length=200, verbose_name='Current last name of child/Children being adopted'),
        ),
        migrations.AlterField(
            model_name='case',
            name='your_name',
            field=models.CharField(max_length=200, verbose_name='Last Name of adopting Parent'),
        ),
        migrations.AddField(
            model_name='document',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Case'),
        ),
    ]
